from Lab9.binary_search_tree import *

BST_tree = Node(30)
BST_tree.insert(Node(15))
BST_tree.insert(Node(14))
BST_tree.insert(Node(17))
BST_tree.insert(Node(13))
BST_tree.insert(Node(23))
BST_tree.insert(Node(10))
BST_tree.insert(Node(19))
BST_tree.insert(Node(12))
BST_tree.insert(Node(34))
BST_tree.insert(Node(9))
BST_tree.insert(Node(45))
BST_tree.insert(Node(40))
BST_tree.insert(Node(55))
BST_tree.insert(Node(1))
BST_tree.insert(Node(3))
print("My min in tree:",bst_min(BST_tree))
print("My max in tree:",bst_max(BST_tree))
